### ISSUE TITLE
GPU Exception while training

### ISSUE THREAD

**Issue by Wil-Lee** [cgaueb/nss#2]
Hi,
I'm currently trying to run your code on my machine with the following setup: i7 4790k, RTX 2080 8GB, 16 GB DDR3
Win10 WSL2 Ubuntu 22
Running the code solely on the CPU works fine, but trying to run the code with GPU support results in an exception.
I'm using tf 2.10.1 with cuda 11.2 and cudnn 8.1.

Note that I'm only using the bathroom 1 and 2 sah dataset. I've adapted the related files accordingly.

The error happens always during the second batch at https://github.com/cgaueb/nss/blob/649ce19ef44922f0286b9dac5a5ce5258c4b67e6/neural_spatial_split.py#L158
with the exception:

> Exception has occurred: UnknownError
> Exception encountered when calling layer "tree_level_encoder_0" "                 f"(type recursive_tree_level_encoder).
> 
> Graph execution error:
> 
> CUDNN_STATUS_INTERNAL_ERROR
> in tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
> 	 [[{{node cluster_0_1/xla_run}}]] [Op:__inference_call_765]
> 
> Call arguments received by layer "tree_level_encoder_0" "                 f"(type recursive_tree_level_encoder):
>   • input=['tf.Tensor(shape=(1, 2048, 3), dtype=float32)', 'tf.Tensor(shape=(1, 6), dtype=float32)']
> tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:
> 
> CUDNN_STATUS_INTERNAL_ERROR
> in tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
> 	 [[{{node cluster_0_1/xla_run}}]] [Op:__inference_call_765]
> 
> During handling of the above exception, another exception occurred: \<call stack\>
> 
> tensorflow.python.framework.errors_impl.UnknownError: Exception encountered when calling layer "tree_level_encoder_0" "                 f"(type recursive_tree_level_encoder).
> 
> Graph execution error:
> 
> CUDNN_STATUS_INTERNAL_ERROR
> in tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
> 	 [[{{node cluster_0_1/xla_run}}]] [Op:__inference_call_765]
> 
> Call arguments received by layer "tree_level_encoder_0" "                 f"(type recursive_tree_level_encoder):
>   • input=['tf.Tensor(shape=(1, 2048, 3), dtype=float32)', 'tf.Tensor(shape=(1, 6), dtype=float32)']

Changing the batch size didn’t resolve the issue.
I'm not quite sure if I'm running out of VRAM. I've set memory_growth to true and according to my monitoring software only 2/8 Gb of VRAM is used.

Do you have any suggestions for resolving this issue? I’m new to TensorFlow, and my investigations haven’t led to a solution.

Thanks!

**Comment by IordanisEu** [comment]
Hi,

For tensorflow 2.10.1 and cuda 11.2.2 you need to install cudnn 8.2.1 (not 8.1). I have confirmed that the training process is properly executing for both RTX 2080ti and RTX 3080ti. Unfortunately, that is the only hardware I got access to at the moment. 

Moreover, if you want to train for a 6lvls deep model, utiliing the 2080 VRAM under these default settings in global_config.py I am afraid it will not suffice. You will have to either reduce the point cloud size, batch size or, model capacity (128 in this case). Or employ some other deffered training scheme (e.g. gradient accumulation).

**Comment by Wil-Lee** [comment]
This worked, thank you very much!
